name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4

      - name: Run deploy script
        run: |
          bash ./deploy/build.sh /tmp/linux.zip


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/linux.zip
          make_latest: true
